using System;
using System.Text;

namespace SimpleTypedLocalizer.SourceGenerator;

/*
[ImportLocalizedTextFiles("Assets/Languages/LanguageResource.*.json", ImportType.DumpAsStaticDictionaryInCompileTime)]
[ImportLocalizedTextFiles("Assets/Languages/LanguageResource.*.resx", ImportType.LoadAsEmbbedResourceInRuntime, NameSpace = "SimpleTypedLocalizer")]
public class LanguageResource
{
    private static readonly LocalizerManager manager;

    static LanguageResource()
    {
        manager = new LocalizerManager(new[]
        {
            _LocalizedTextProvider_Assets_Languages_LanguageResource_zh_ch_json_.Instance,
            LocalizedTextProvider.LoadFromEmbbedResource("avares://SimpleTypedLocalizer/Assets/Languages/LanguageResource.jp.resx"),
            LocalizedTextProvider.LoadFromEmbbedResource("avares://SimpleTypedLocalizer/Assets/Languages/LanguageResource.de.resx")
        });
    }

    public static string Name => manager.GetLocalizedText(nameof(Name));
    public static string ValueDescription => manager.GetLocalizedText(nameof(ValueDescription));

    public static NotifiableLanguageResource Notifiable { get; } = new();

    public class NotifiableLanguageResource
    {
        public static ILocalizedTextSource Name => manager.GetLocalizedTextSource(nameof(LanguageResource.Name));
        public static ILocalizedTextSource ValueDescription => manager.GetLocalizedTextSource(nameof(LanguageResource.ValueDescription));
    }
}
*/

public static class ImportTaskSourceWriter
{
    public static string GenerateExtensionClass(LocalizeImportTaskContext context, RunTaskContextResult result)
    {
        var codeBuilder = new IndentedStringBuilder();
        codeBuilder
            .AppendLine("// <auto-generated />")
            .AppendLine($"// generated time: {DateTime.Now}")
            .AppendLine("using System;")
            .AppendLine("using System.Globalization;")
            .AppendLine("using System.Collections.Generic;")
            .AppendLine("using System.CodeDom.Compiler;")
            .AppendLine("using System.Text;")
            .AppendLine("using SimpleTypedLocalizer;")
            .AppendLine();

        if (!string.IsNullOrWhiteSpace(context.TargetNameSpace))
            codeBuilder
                .AppendLine($"namespace {context.TargetNameSpace};")
                .AppendLine();

        codeBuilder
            .AppendLine("[GeneratedCode(\"SimpleTypedLocalizer\", \"0.0.1\")]")
            .AppendLine($"{context.TargetClassAccessibility} partial class {context.TargetClassName}")
            .AppendLine("{")
            .IncrementIndent();

        codeBuilder
            .AppendLine(
                "private static readonly LocalizerManager manager = new LocalizerManager(new LocalizedTextProvider[]{")
            .IncrementIndent();

        GenerateLocalizedTextProvider(result, codeBuilder);

        codeBuilder
            .DecrementIndent()
            .AppendLine("});")
            .AppendLine();

        GenerateLocalizedTextProperties(context, result, codeBuilder, false);
        codeBuilder.AppendLine();

        codeBuilder
            .AppendLine("public static NotifiableLanguageResource Notifiable { get; } = new();")
            .AppendLine();
        codeBuilder
            .AppendLine("public static LocalizerManager LocalizerManager => manager;")
            .AppendLine();

        codeBuilder
            .AppendLine("public class NotifiableLanguageResource")
            .AppendLine("{")
            .IncrementIndent();

        GenerateLocalizedTextProperties(context, result, codeBuilder, true);

        codeBuilder
            .DecrementIndent()
            .AppendLine("}")
            .AppendLine();

        GenerateStaticBuildProviders(result, codeBuilder);

        codeBuilder
            .DecrementIndent()
            .AppendLine("}")
            .AppendLine();

        return codeBuilder.ToString();
    }

    private static void GenerateStaticBuildProviders(RunTaskContextResult result,
        IndentedStringBuilder codeBuilder)
    {
        foreach (var staticBuildProvider in result.StaticBuildProviders)
            GenerateStaticBuildProvider(codeBuilder, staticBuildProvider);
    }

    private static void GenerateStaticBuildProvider(IndentedStringBuilder codeBuilder,
        RunTaskContextResult.StaticBuildProvider staticBuildProvider)
    {
        codeBuilder
            .AppendLine($"private static class {staticBuildProvider.ProviderClassName}")
            .AppendLine("{")
            .IncrementIndent();

        codeBuilder
            .AppendLine(
                $"public static readonly LocalizedTextProvider Instance = new LocalizedTextProvider(CultureInfo.GetCultureInfo(\"{staticBuildProvider.ProviderLangCode}\"),")
            .AppendLine("new Dictionary<string, string>(){")
            .IncrementIndent();

        foreach (var pair in staticBuildProvider.LangMap)
            codeBuilder.AppendLine(
                $" [\"{pair.Key}\"] = Encoding.UTF8.GetString(Convert.FromBase64String(\"{Convert.ToBase64String(Encoding.UTF8.GetBytes(pair.Value))}\"))  ,");

        codeBuilder
            .DecrementIndent()
            .AppendLine("});");

        codeBuilder
            .DecrementIndent()
            .AppendLine("}")
            .AppendLine();
    }

    private static string EscapeLineBreaks(string input)
    {
        if (string.IsNullOrEmpty(input)) return input;
        return input.Replace("\r\n", "\\n").Replace("\n", "\\n");
    }

    /// <summary>
    ///     123123
    /// </summary>
    private static void GenerateLocalizedTextProperties(LocalizeImportTaskContext context, RunTaskContextResult result,
        IndentedStringBuilder codeBuilder, bool isGenerateTextSource)
    {
        foreach (var pair in result.ExportLocalizedTextNames)
        {
            var typeName = isGenerateTextSource ? "ILocalizedTextSource" : "string";
            var methodName = isGenerateTextSource ? "GetLocalizedTextSource" : "GetLocalizedText";
            var isStatic = isGenerateTextSource ? "" : "static ";

            var textName = pair.Key;

            var textDefaultValue = EscapeLineBreaks(pair.Value);

            codeBuilder.AppendLine("/// <summary>");
            codeBuilder.AppendLine(
                $"/// get localized text {(isGenerateTextSource ? "source " : "")}named <c>{textName}</c>, default localized value: <c>{textDefaultValue}</c><br/>");
            if (isGenerateTextSource)
            {
                codeBuilder.AppendLine(
                    "/// it's a text source which implement INotifyPropertyChanged and design for data binding");
                codeBuilder.AppendLine(
                    "/// <example><code>");
                codeBuilder.AppendLine(
                    $"/// &lt;TextBlock Text=\"{{Text, Source={{x:Static lang:{context.TargetClassName}.Notifiable.{textName}}}}}\"/&gt;");
                codeBuilder.AppendLine(
                    "/// </code></example>");
            }

            codeBuilder.AppendLine("/// </summary>");
            codeBuilder.AppendLine(
                $"public {isStatic}{typeName} {textName} => manager.{methodName}(nameof({textName}));");
        }
    }

    private static void GenerateLocalizedTextProvider(RunTaskContextResult result,
        IndentedStringBuilder codeBuilder)
    {
        foreach (var declareSourceSentence in result.ProviderDeclareSourceSentences)
            codeBuilder.AppendLine(declareSourceSentence + ",");
    }
}